name: Push docker manually

on:
  workflow_dispatch:
    inputs:
      kubernetesVersion:
        description: 'Kubernetes version'
        required: true
        default: 'v1.27.0'
        type: string
      latest:
        description: 'docker image latest tag'
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      K8S_VERSION: ${{ github.event.inputs.kubernetesVersion }}
      LATEST:      ${{ github.event.inputs.latest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login docker-hub
        uses: docker/login-action@v2
        with:
          username: ghilbut
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make docker tags
        id: tags
        run: |
          token=$VERSION
          check=${token//v[!0-9]/ }
          semver=(${check//\./ })
          
          image="ghilbut/kubectl"
          major=${semver}
          minor=${semver[1]}
          patch=${semver[2]}

          echo "TAG_LONG_VERSION=-t ${image}:${K8S_VERSION}" >> $GITHUB_ENV
          echo "TAG_SHORT_VERSION=-t ${image}:${major}.${minor}" >> $GITHUB_ENV
          if [ $LATEST = "true" ]
          then
            echo "TAG_LATEST=-t ${image}:latest" >> $GITHUB_ENV
          fi
        env:
          VERSION: ${{ env.K8S_VERSION }}
          LATEST:  ${{ env.LATEST }}

      - name: Build and Push
        run: docker buildx build
                    --platform linux/amd64,linux/arm64
                    --build-arg K8S_VERSION=${{ env.K8S_VERSION }}
                    --target release
                    --push
                    ${{ env.TAG_LONG_VERSION }}
                    ${{ env.TAG_SHORT_VERSION }}
                    ${{ env.TAG_LATEST }} .
